query VoteCreateById($id: ID = "") {
    voteCreated(id: $id) {
        blockTimestamp
        transactionHash
        voteId
        endTime
        options
    }
}

query VoteCreateByAddress($address: Bytes = "") {
    voteCreateds(orderBy: blockNumber,orderDirection: desc,where: {creator: $address}) {
        blockTimestamp
        transactionHash
        voteId
        endTime
        options
    }
}

query VoteByVoteId($voteId: Bytes = "") {
    voteCreateds(where: {voteId: $voteId}) {
        blockTimestamp
        transactionHash
        voteId
        endTime
        options
    }
}

query VoteCastByVoteId($voteId: Bytes = "") {
    voteCasteds(orderBy: blockNumber, where: {voteId: $voteId}) {
        blockTimestamp
        transactionHash
        voter
        option
    }
}
